-- MySQL Script generated by MySQL Workbench
-- Qui 02 Jul 2015 11:41:46 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Diarias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Diarias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Diarias` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Diarias` ;

-- -----------------------------------------------------
-- Table `Diarias`.`TB_orgao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`TB_orgao` (
  `cod` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diarias`.`TB_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`TB_unidade` (
  `cod` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diarias`.`TB_funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`TB_funcao` (
  `cod` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diarias`.`TB_programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`TB_programa` (
  `cod` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diarias`.`TB_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`TB_acao` (
  `cod` CHAR(4) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `linguagem_cidada` VARCHAR(200) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diarias`.`TB_favorecido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`TB_favorecido` (
  `cpf` CHAR(15) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diarias`.`TB_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`TB_pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento_pagamento` CHAR(12) NOT NULL,
  `gestao` INT NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `valor` FLOAT NOT NULL,
  `cpf_favorecido` CHAR(15) NOT NULL,
  `cod_unidade` INT NOT NULL,
  `cod_funcao` INT NOT NULL,
  `cod_orgao` INT NOT NULL,
  `cod_programa` INT NOT NULL,
  `cod_acao` CHAR(4) NOT NULL,
  `cod_sub_org` INT NOT NULL,
  `cod_sub_func` INT NOT NULL,
  INDEX `fk_TB_pagamento_TB_favorecido1_idx` (`cpf_favorecido` ASC),
  INDEX `fk_TB_pagamento_TB_unidade1_idx` (`cod_unidade` ASC),
  INDEX `fk_TB_pagamento_TB_funcao1_idx` (`cod_funcao` ASC),
  INDEX `fk_TB_pagamento_TB_orgao1_idx` (`cod_orgao` ASC),
  INDEX `fk_TB_pagamento_TB_programa1_idx` (`cod_programa` ASC),
  INDEX `fk_TB_pagamento_TB_acao1_idx` (`cod_acao` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_TB_pagamento_TB_orgao2_idx` (`cod_sub_org` ASC),
  INDEX `fk_TB_pagamento_TB_funcao2_idx` (`cod_sub_func` ASC),
  CONSTRAINT `fk_TB_pagamento_TB_favorecido1`
    FOREIGN KEY (`cpf_favorecido`)
    REFERENCES `Diarias`.`TB_favorecido` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_pagamento_TB_unidade1`
    FOREIGN KEY (`cod_unidade`)
    REFERENCES `Diarias`.`TB_unidade` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_pagamento_TB_funcao1`
    FOREIGN KEY (`cod_funcao`)
    REFERENCES `Diarias`.`TB_funcao` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_pagamento_TB_orgao1`
    FOREIGN KEY (`cod_orgao`)
    REFERENCES `Diarias`.`TB_orgao` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_pagamento_TB_programa1`
    FOREIGN KEY (`cod_programa`)
    REFERENCES `Diarias`.`TB_programa` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_pagamento_TB_acao1`
    FOREIGN KEY (`cod_acao`)
    REFERENCES `Diarias`.`TB_acao` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_pagamento_TB_orgao2`
    FOREIGN KEY (`cod_sub_org`)
    REFERENCES `Diarias`.`TB_orgao` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_pagamento_TB_funcao2`
    FOREIGN KEY (`cod_sub_func`)
    REFERENCES `Diarias`.`TB_funcao` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Diarias` ;

-- -----------------------------------------------------
-- Placeholder table for view `Diarias`.`V_gastoPorUnidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diarias`.`V_gastoPorUnidade` (`nome` INT, `valor` INT);

-- -----------------------------------------------------
-- View `Diarias`.`V_gastoPorUnidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Diarias`.`V_gastoPorUnidade`;
USE `Diarias`;
CREATE  OR REPLACE VIEW `V_gastoPorUnidade` AS
    SELECT 
        nome, SUM(valor) AS valor
    FROM
        TB_pagamento,
        TB_unidade
    WHERE
        cod = cod_unidade
    GROUP BY cod_unidade;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
